### ISSUE TITLE
Plex - "Song Import Failed - The server could not be reached"

### ISSUE THREAD

**Issue by wolleydev** [timusus/Shuttle2#130]
## 🌎 Environment

- Device: Oppo A54 5G
- OS: Android 13
- App Version & Build: 1.0.6

## 💬 Description

I have added my Plex Server as a source.
The authentification to the server works just fine, which I suppose means the server is reachable. I am using a local ip (192.168...) with a port number as the url.
The new device shows up in my Plex account as well, albeit as an empty device without any name or info

However, I am not able to scan the media library.  I get the error message "Song Import failed - The server could not be reached"

Evidently the server can be reached because I was able to login.

## 🦶 Reproduction Steps

1. Add a locally hosted Plex as a media source
2.  Enter URL and login
3. Try to scan the library

## 🤔 Expected Results

Library should be scanned

## 😲 Actual Results

Song import failed
Server could not be reached

## 📸 Screenshots

![Device shows as empty in Plex account](https://github.com/timusus/Shuttle2/assets/130301036/f1ef0b7a-4650-4bc3-aa68-cab8c3951600)
![Song import failed - the server could not be reached](https://github.com/timusus/Shuttle2/assets/130301036/bf3cbf6b-5520-4121-b01f-ecec5a29e713)

## 📎 Attachments

###Debug logs
```
07:22:53.059
2/f
PlaybackInitializer.init()

07:22:53.061
2/l
Initializing trial manager

07:22:53.399
5/f
Queue restoration failed: queue position null

07:22:53.400
2/f
Queue restored in 1ms (Time since app init: 341ms)

07:22:53.400
2/g
load(seekPosition: 0)

07:22:53.401
6/g
Load failed - no current queue item

07:22:53.401
2/d
onQueueRestored()

07:22:53.401
2/k
updateQueue()

07:22:53.411
2/k
updateCurrentQueueItem()

07:22:53.568
4/f$c
trialState changed to Unknown

07:22:53.717
2/l$a
Billing client available

07:22:54.455
4/f
Retrieved remote device

07:22:54.456
4/f$c
trialState changed to Trial(timeRemaining=1192133380)

07:23:32.598
3/b
authenticate(address: 192.168.REDACTED)

07:24:58.302
2/f
Starting import..

07:24:58.357
6/d$a
The server could not be reached.
NetworkError (hasInternetConnectivity: true, error: Failed to connect to localhost/127.0.0.1:80)
	at nb.c$a.b(SourceFile:35)
	at jj.q$a.f(SourceFile:5)
	at yi.e$a.run(SourceFile:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

07:24:58.876
2/f
Import complete in 570ms)
```

**Comment by timusus** [comment]
"Server cannot be reached" means that the address you have used is incorrect. 

`localhost` is probably not the address you want - unless your Plex server is running on the Android device itself.

Not sure if port 80 is correct either.
