### ISSUE TITLE
Issues with Cp1251-encoded metadata decoding

### ISSUE THREAD

**Issue by zhelanov** [timusus/Shuttle2#131]
## 🌎 Environment

- Environment: Production
- Device: Sony Xperia 10 IV
- OS: Android 13
- App Version & Build: 1.0.6 (10060053)
- Possible Cause: None

## 💬 Description

It seems that the app has some issues with Cyrillic encoding (WINDOWS-1251, for instance). At the same time, I don't see the same problem in the other players (tested in InShot's "Music Player & MP3 Player")

## 🦶 Reproduction Steps

1. Download some audiobook with Cyrillic metadata
2. Scan it with S2 Media Provider

## 🤔 Expected Results

You see something like `Луций Анней Сенека` in your library

## 😲 Actual Results

You see something like `Ëóöèé Àííåé Ñåíåêà` in your library

## 📸 Screenshots

Example screenshot: https://imgur.com/a/YQRaFTm

**Comment by timusus** [comment]
@zhelanov could you please provide a sample file so I can replicate the issue?

**Comment by zhelanov** [comment]
Hi @timusus ,
Sure, here go two examples: https://disk.yandex.ru/d/DewqQVj7mO5KQw https://disk.yandex.ru/d/YjN91NwvxNhQAw

**Comment by timusus** [comment]
[009 - 9.mp3.zip](https://github.com/timusus/Shuttle2/files/13473149/009.-.9.mp3.zip)

**Comment by timusus** [comment]
Interestingly, when I preview this file on my Mac, I see the same problem:
![image](https://github.com/timusus/Shuttle2/assets/4422616/037a81a3-eb42-4a2f-8378-558469d71811)

**Comment by timusus** [comment]
I don't know much about encoding. If I had to guess, the problem exists in the tags themselves, rather than in S2.

**Comment by timusus** [comment]
Update: I've had a look into this. The issue is that the character encoding appears to be Windows-1251, but it's detected as ISO-8859-1. A possible solution is to update [KTagLib](https://github.com/timusus/ktaglib) to include ICU4c, detect the charset, and convert to UTF-8.

It's pretty involved. @zhelanov if you're looking for a quick fix, you might use a tag editor to re-encode your tags as UTF-8.

**Comment by zhelanov** [comment]
Hey @timusus , 
thanks for the response! So I actually already did it - I've made a batch update of the tags, and it solved the problem. Sorry to bother you - I haven't seen the problem in another music player, so I decided that Shuttle2 doesn't work with non-UTF-8 encoding properly.
Thanks again!
