### ISSUE TITLE
Disc# support

### ISSUE THREAD

**Issue by martingem** [timusus/Shuttle2#132]
## 💬  User story

`I would like to see the albums separated, somehow...`

![image](https://github.com/timusus/Shuttle2/assets/2473921/f55df9d3-48c5-4194-beb9-66a874b4b201)

## 📝 Notes

It would be great to have the Disc Number functionality back in S2!

Currently, the only way to make that work is to create separate folders i.e. as if they're different albums and name them differently (Album Title - Disc 1, and so on). I have multiple OSTs of games and they all experience the same issue in S2 compared to Shuttle+.

## 👩‍🎨 Visual Design

As long as it's separated, I'm good.

## 👩‍🔧 Technical Design Notes

N/A

## 🤝 Relationships

N/A

**Comment by timusus** [comment]
Which Media Provider are you using? I'm guessing it's the Android Media Store. Try changing to the Shuttle Media Provider.

**Comment by martingem** [comment]
@timusus thank you so much, it was exactly that. Love the app, thank you!
