### ISSUE TITLE
Subsonic integration

### ISSUE THREAD

**Issue by Insightbr** [timusus/Shuttle2#52]
Hi, loving the app design and the recent open source change. I recently moved from Jellyfin to Navidrome for my music needs. It would be cool to have more options for good, modern, feature rich Subsonic compatible apps that are open source. Thanks for your work!

**Comment by timusus** [comment]
I'm going to close this one - I don't think there's enough demand for this, and it would take a fair bit of effort.

I'm not realistically going to solve this - so I'll close it. Can reopen if there is more demand or another dev would like to work on it.
