### ISSUE TITLE
Media from Plex fails to import

### ISSUE THREAD

**Issue by simeonrobinson** [timusus/Shuttle2#91]
## 🌎 Environment

- Environment: Production 
- Device: e.g. Google Pixel 7
- OS: Android 13
- App Version & Build: 1.0.4

## 💬 Description

Music from my local Plex server can't be added after adding it as a source and authenticating 
## 🦶 Reproduction Steps

1. Add Plex server as a media source
2. Rescan media library

## 🤔 Expected Results

Music on my Plex server populates my media library

## 😲 Actual Results
S2 fails to add media with an unexpected error message

## 📸 Screenshots
![Screenshot_20221207-045131](https://user-images.githubusercontent.com/72761033/206146522-214f585b-b9e3-484d-9117-6f726f823f52.png)

## Debug log
https://pastebin.com/7XpNRpKr

**Comment by timusus** [comment]
@simeonrobinson can you try enabling logging from the settings menu (settings -> debug -> debug logging), then try a Plex import, then copy the logs. You might want to redact some information (like your full server address) before sharing here.

**Comment by simeonrobinson** [comment]
Here's the full log after trying a Plex import https://pastebin.com/wpSZSPGF

**Comment by timusus** [comment]
Thakns for the logs @simeonrobinson 

This is fixed in 1.0.7-beta1 (available soon in beta testing)

**Comment by simeonrobinson** [comment]
I enrolled in the beta a few days ago and Plex import seems to be working for me now. Thanks for the help!

**Comment by JaxzKyd** [comment]
I'm on the beta, but my Plex import keeps failing...

**Comment by timusus** [comment]
@JaxzKyd can you do the same as simeon..

> enable logging from the settings menu (settings -> debug -> debug logging), then try a Plex import, then copy the logs. You might want to redact some information (like your full server address) before sharing here.

If you can share the logs, I'll be able to quickly identify the issue and fix.

**Comment by JaxzKyd** [comment]
```
07:07:45.506
2/f
Starting import..

07:07:45.546
6/d$a
The server could not be reached.
NetworkError (hasInternetConnectivity: true, error: Connection reset)
	at bc.c$a.b(SourceFile:35)
	at zj.r$a.c(SourceFile:5)
	at oj.e$a.run(SourceFile:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


07:07:46.056
2/f
Import complete in 549ms)

```

**Comment by timusus** [comment]
@JaxzKyd it looks like your server address or port is incorrect. You can share the details here if you’re happy to (maybe screenshot your config screen), or otherwise dm me on Discord and I can assist.

**Comment by JaxzKyd** [comment]
Oops, had it on http instead of https, but still no give and I double checked the url I had in and it worked (https://imgur.com/a/atts3I6) 

After changing it to https tho I did get a different log output


```
11:10:21.743
3/b
authenticate(address: HTTPS:// REDACTED:32400)

11:10:24.361
2/f
Starting import..

11:10:24.429
6/d$a
The server could not be reached.
NetworkError (hasInternetConnectivity: true, error: Hostname REDACTED not verified:
    certificate: sha256/iyu+cI4Wbh1gxn2EJHxWAr58oQ7cYEtOGw03mDsPdo8=
    DN: CN=*.ddc0ac4b095a4ae3b98796987ab94ec8.plex.direct
    subjectAltNames: [*.ddc0ac4b095a4ae3b98796987ab94ec8.plex.direct])
	at bc.c$a.b(SourceFile:35)
	at zj.r$a.c(SourceFile:5)
	at oj.e$a.run(SourceFile:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


11:10:24.935
2/f
Import complete in 573ms)
```

**Comment by timusus** [comment]
@JaxzKyd are you sure your server uses ssl (https). The error looks like a certificate problem. I don’t think these are S2 issues. Going to close this issue. Feel free to file another one if needed. Or dm me on discord
